# Generated by Django 4.0.5 on 2022-08-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('tip', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('indian', models.BooleanField()),
                ('anonymously', models.BooleanField()),
                ('provider_order_id', models.CharField(max_length=40, verbose_name='Order ID')),
                ('payment_id', models.CharField(max_length=36, verbose_name='Payment ID')),
                ('signature_id', models.CharField(max_length=128, verbose_name='Signature ID')),
                ('status', models.CharField(default='Pending', max_length=254, verbose_name='Payment Status')),
            ],
        ),
    ]
