# Generated by Django 4.0.5 on 2022-09-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='last_login',
            field=models.TimeField(default='09:49:22'),
        ),
    ]
