# Generated by Django 4.0.5 on 2022-09-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0002_newuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='last_login',
        ),
    ]
